spring.application.name=jwt-auth-practice

spring.datasource.url=jdbc:postgresql://localhost:5432/Test_CRUDJWT
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true